import type { StepDef, InscriptionState } from "./types";

export const STEPS: StepDef[] = [
  { id: 1, title: "Compte hôtelier", sub: "Identité du gérant", icon: "user" },
  { id: 2, title: "Établissement", sub: "Carte d'identité", icon: "building" },
  { id: 3, title: "Équipements", sub: "Services généraux", icon: "sparkles" },
  { id: 4, title: "Types de chambres", sub: "Inventaire & médias", icon: "bed" },
  { id: 5, title: "Valeurs ajoutées", sub: "Restaurant, bar, spa…", icon: "utensils" },
  { id: 6, title: "Tarification", sub: "Paiement & conditions", icon: "creditCard" },
  { id: 7, title: "Récapitulatif", sub: "Vérification & publication", icon: "rocket" },
];

export const INITIAL_STATE: InscriptionState = {
  account: {
    fullName: "",
    phone: "",
    email: "",
    rccm: "",
    idCardFrontFileId: null,
    idCardBackFileId: null,
    acceptedTerms: false,
  },
  hotel: {
    name: "",
    type: "",
    stars: 0,
    address: "",
    villeId: null,
    villeName: "",
    communeId: null,
    communeName: "",
    phone: "",
    email: "",
    website: "",
    instagram: "",
    facebook: "",
    yearOpened: "",
    capacity: "",
    languages: [],
    shortDesc: "",
    longDesc: "",
    strengths: [],
    coverFileId: null,
    galleryFileIds: [],
    videoFileId: null,
    droneVideoFileId: null,
    lat: 5.345,
    lng: -4.005,
  },
  equip: {
    wifi: false, wifiFree: false,
    aircon: false, hotWater: false,
    security247: false, cctv: false,
    parking: false,
    safe: false, accessBadge: false,
    reception247: false, laundry: false,
    shuttle: false, carRental: false,
    concierge: false, roomService: false,
    breakfastInRoom: false, dailyCleaning: false,
    pool: false, gym: false, spa: false,
    sports: false, kids: false, garden: false,
    conference: false, coworking: false,
    printer: false, secretariat: false,
  },
  roomTypes: [],
  valueAdds: {
    restaurant: { configured: false, isOpenToPublic: true, imageIds: [] },
    bar:        { configured: false, isOpenToPublic: true, imageIds: [] },
    pool:       { configured: false, isOpenToPublic: true, imageIds: [] },
    gym:        { configured: false, isOpenToPublic: true, imageIds: [] },
    spa:        { configured: false, isOpenToPublic: true, imageIds: [] },
    conference: { configured: false, isOpenToPublic: true, imageIds: [] },
    outdoor:    { configured: false, isOpenToPublic: true, imageIds: [] },
    customSpaces: [],
  },
  services: {
    transferAirport: true, transferPrice: 15000,
    rental: true, laundryService: true, laundryPrice: 5000,
    babysit: false, excursions: true, infirmary: false,
    exchange: false, atm: true, shop: false, printing: true,
  },
  pricing: {
    payWave: true, payOM: true, payCard: true, payCash: true,
    depositRequired: true, depositPct: 30,
    cancelPolicy: "Modérée",
    kidsFree: 7,
    cribAvailable: true,
    cribPaid: false,
    pets: false,
    smoking: "Zone extérieure uniquement",
    cityTax: 1500,
    earlyCheckin: "Sur disponibilité",
    lateCheckout: "Sur disponibilité",
  },
};

export const EQUIP_GROUPS = [
  {
    id: "conn",
    title: "Connectivité & confort",
    icon: "wifi",
    color: "primary",
    items: [
      { id: "wifi", label: "Wi-Fi établissement", sub: "Toutes zones couvertes" },
      { id: "wifiFree", label: "Wi-Fi gratuit pour les clients", sub: "Sinon : payant" },
      { id: "aircon", label: "Climatisation", sub: "Toutes les chambres" },
      { id: "hotWater", label: "Eau chaude permanente", sub: "24h/24" },
    ],
  },
  {
    id: "sec",
    title: "Sécurité",
    icon: "shield",
    color: "violet",
    items: [
      { id: "security247", label: "Gardiennage 24h/24", sub: "Agents de sécurité sur site" },
      { id: "cctv", label: "Caméras de surveillance", sub: "Espaces communs" },
      { id: "parking", label: "Parking sécurisé", sub: "Préciser la capacité" },
      { id: "safe", label: "Coffre-fort à la réception", sub: "Pour les clients" },
      { id: "accessBadge", label: "Accès sécurisé", sub: "Badge ou digicode" },
    ],
  },
  {
    id: "serv",
    title: "Services hôteliers",
    icon: "users",
    color: "teal",
    items: [
      { id: "reception247", label: "Réception 24h/24", sub: "Ou horaires limités" },
      { id: "laundry", label: "Blanchisserie / pressing" },
      { id: "shuttle", label: "Service de navette", sub: "Aéroport, centre-ville" },
      { id: "carRental", label: "Location de véhicules", sub: "Partenaire moto-taxi" },
      { id: "concierge", label: "Conciergerie" },
      { id: "roomService", label: "Room service" },
      { id: "breakfastInRoom", label: "Petit-déjeuner en chambre" },
      { id: "dailyCleaning", label: "Ménage quotidien" },
    ],
  },
  {
    id: "leis",
    title: "Loisirs & bien-être",
    icon: "waves",
    color: "amber",
    items: [
      { id: "pool", label: "Piscine", sub: "Intérieure / extérieure" },
      { id: "gym", label: "Salle de sport / fitness" },
      { id: "spa", label: "Spa, hammam, sauna" },
      { id: "sports", label: "Terrains de sport", sub: "Tennis, basket…" },
      { id: "kids", label: "Espace enfants" },
      { id: "garden", label: "Jardin / terrasse" },
    ],
  },
  {
    id: "biz",
    title: "Business & événements",
    icon: "briefcase",
    color: "pink",
    items: [
      { id: "conference", label: "Salle de conférence" },
      { id: "coworking", label: "Espace coworking" },
      { id: "printer", label: "Imprimante / photocopieur" },
      { id: "secretariat", label: "Services de secrétariat" },
    ],
  },
];
