import type { StepDef, InscriptionState } from "./types";

export const STEPS: StepDef[] = [
  { id: 1, title: "Compte hôtelier", sub: "Identité du gérant", icon: "user" },
  { id: 2, title: "Établissement", sub: "Carte d'identité", icon: "building" },
  { id: 3, title: "Équipements", sub: "Services généraux", icon: "sparkles" },
  { id: 4, title: "Types de chambres", sub: "Inventaire & médias", icon: "bed" },
  { id: 5, title: "Valeurs ajoutées", sub: "Restaurant, bar, spa…", icon: "utensils" },
  { id: 6, title: "Tarification", sub: "Paiement & conditions", icon: "creditCard" },
  { id: 7, title: "Récapitulatif", sub: "Vérification & publication", icon: "rocket" },
];

export const INITIAL_STATE: InscriptionState = {
  account: {
    fullName: "Aïcha Diabaté",
    phone: "+225 07 58 42 33 19",
    email: "aicha.diabate@residence-lagune.ci",
    rccm: "CI-ABJ-2023-B-12847",
    idCardFrontFileId: "mock-front-id",
    idCardBackFileId: null,
    acceptedTerms: false,
  },
  hotel: {
    name: "Résidence Lagune Bleue",
    type: "hotel",
    stars: 4,
    address: "Boulevard Lagunaire",
    commune: "Cocody",
    city: "Abidjan",
    phone: "+225 27 22 48 75 60",
    email: "contact@residence-lagune.ci",
    website: "www.residence-lagune.ci",
    instagram: "@lagunebleueabj",
    facebook: "Résidence Lagune Bleue",
    yearOpened: "2019",
    capacity: 42,
    languages: ["Français", "Anglais", "Dioula"],
    shortDesc: "Hôtel de charme face à la lagune Ébrié, à 15min de l'aéroport.",
    longDesc: "Niché entre le centre des affaires du Plateau et les plages de Bassam, la Résidence Lagune Bleue offre une expérience hôtelière haut de gamme dans un cadre paisible. Nos 42 chambres et suites donnent toutes sur la lagune ou nos jardins tropicaux.",
    strengths: ["Vue lagune", "Calme", "Proximité aéroport", "Cuisine ivoirienne"],
    coverPhoto: true,
    galleryCount: 8,
    hasVideo: false,
    hasDrone: false,
    lat: 5.358,
    lng: -3.989,
  },
  equip: {
    wifi: true, wifiFree: true,
    aircon: true, hotWater: true,
    security247: true, cctv: true,
    parking: true,
    safe: true, accessBadge: true,
    reception247: true, laundry: true,
    shuttle: true, carRental: false,
    concierge: true, roomService: true,
    breakfastInRoom: true, dailyCleaning: true,
    pool: true, gym: true, spa: true,
    sports: false, kids: false, garden: true,
    conference: true, coworking: false,
    printer: true, secretariat: false,
  },
  roomTypes: [
    {
      id: "rt-1",
      name: "Chambre Standard",
      totalRooms: 18, surface: 22, floors: "1 → 3",
      bedType: "Grand lit (Queen)", bedCount: 1, maxOccupancy: 2,
      basePrice: 38000, weekendPrice: 42000, longStayPrice: 32000,
      breakfastOption: "included", photos: 6, hasVideo: true,
      view: "Jardin",
      complete: true, cover: "rt-cover-1",
    },
    {
      id: "rt-2",
      name: "Chambre Supérieure Vue Lagune",
      totalRooms: 14, surface: 28, floors: "2 → 4",
      bedType: "Grand lit (King)", bedCount: 1, maxOccupancy: 2,
      basePrice: 55000, weekendPrice: 62000, longStayPrice: 48000,
      breakfastOption: "included", photos: 8, hasVideo: true,
      view: "Lagune",
      complete: true, cover: "rt-cover-2",
    },
    {
      id: "rt-3",
      name: "Suite Junior",
      totalRooms: 8, surface: 42, floors: "3 → 5",
      bedType: "Grand lit (King) + Canapé-lit", bedCount: 2, maxOccupancy: 3,
      basePrice: 95000, weekendPrice: 110000, longStayPrice: 85000,
      breakfastOption: "included", photos: 10, hasVideo: true,
      view: "Lagune",
      complete: true, cover: "rt-cover-3",
    },
    {
      id: "rt-4",
      name: "Suite Présidentielle",
      totalRooms: 2, surface: 78, floors: "5",
      bedType: "Grand lit (King)", bedCount: 1, maxOccupancy: 4,
      basePrice: 220000, weekendPrice: 250000, longStayPrice: 200000,
      breakfastOption: "included", photos: 4, hasVideo: false,
      view: "Panoramique",
      complete: false, cover: "rt-cover-4",
    },
  ],
  valueAdds: {
    restaurant: { configured: true, name: "Le Baobab", cuisine: "Africaine & internationale", priceAvg: 18000 },
    bar: { configured: true, name: "Sky Lounge", type: "Rooftop bar" },
    pool: { configured: true, type: "Extérieure" },
    gym: { configured: false },
    spa: { configured: false },
    conference: { configured: true, rooms: 2, capacity: 80 },
    outdoor: { configured: true },
  },
  services: {
    transferAirport: true, transferPrice: 15000,
    rental: true, laundryService: true, laundryPrice: 5000,
    babysit: false, excursions: true, infirmary: false,
    exchange: false, atm: true, shop: false, printing: true,
  },
  pricing: {
    payWave: true, payOM: true, payCard: true, payCash: true,
    depositRequired: true, depositPct: 30,
    cancelPolicy: "Modérée",
    kidsFree: 7,
    cribAvailable: true,
    cribPaid: false,
    pets: false,
    smoking: "Zone extérieure uniquement",
    cityTax: 1500,
    earlyCheckin: "Sur disponibilité",
    lateCheckout: "Sur disponibilité",
  },
};

export const EQUIP_GROUPS = [
  {
    id: "conn",
    title: "Connectivité & confort",
    icon: "wifi",
    color: "primary",
    items: [
      { id: "wifi", label: "Wi-Fi établissement", sub: "Toutes zones couvertes" },
      { id: "wifiFree", label: "Wi-Fi gratuit pour les clients", sub: "Sinon : payant" },
      { id: "aircon", label: "Climatisation", sub: "Toutes les chambres" },
      { id: "hotWater", label: "Eau chaude permanente", sub: "24h/24" },
    ],
  },
  {
    id: "sec",
    title: "Sécurité",
    icon: "shield",
    color: "violet",
    items: [
      { id: "security247", label: "Gardiennage 24h/24", sub: "Agents de sécurité sur site" },
      { id: "cctv", label: "Caméras de surveillance", sub: "Espaces communs" },
      { id: "parking", label: "Parking sécurisé", sub: "Préciser la capacité" },
      { id: "safe", label: "Coffre-fort à la réception", sub: "Pour les clients" },
      { id: "accessBadge", label: "Accès sécurisé", sub: "Badge ou digicode" },
    ],
  },
  {
    id: "serv",
    title: "Services hôteliers",
    icon: "users",
    color: "teal",
    items: [
      { id: "reception247", label: "Réception 24h/24", sub: "Ou horaires limités" },
      { id: "laundry", label: "Blanchisserie / pressing" },
      { id: "shuttle", label: "Service de navette", sub: "Aéroport, centre-ville" },
      { id: "carRental", label: "Location de véhicules", sub: "Partenaire moto-taxi" },
      { id: "concierge", label: "Conciergerie" },
      { id: "roomService", label: "Room service" },
      { id: "breakfastInRoom", label: "Petit-déjeuner en chambre" },
      { id: "dailyCleaning", label: "Ménage quotidien" },
    ],
  },
  {
    id: "leis",
    title: "Loisirs & bien-être",
    icon: "waves",
    color: "amber",
    items: [
      { id: "pool", label: "Piscine", sub: "Intérieure / extérieure" },
      { id: "gym", label: "Salle de sport / fitness" },
      { id: "spa", label: "Spa, hammam, sauna" },
      { id: "sports", label: "Terrains de sport", sub: "Tennis, basket…" },
      { id: "kids", label: "Espace enfants" },
      { id: "garden", label: "Jardin / terrasse" },
    ],
  },
  {
    id: "biz",
    title: "Business & événements",
    icon: "briefcase",
    color: "pink",
    items: [
      { id: "conference", label: "Salle de conférence" },
      { id: "coworking", label: "Espace coworking" },
      { id: "printer", label: "Imprimante / photocopieur" },
      { id: "secretariat", label: "Services de secrétariat" },
    ],
  },
];
